version: "3"

services:
  server-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "4000:3000"
    networks:
      - roguelike

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: my-db-name
    networks:
      - roguelike

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.11
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - roguelike

volumes:
    pgadmin-data:

networks:
  roguelike:
    driver: bridge
